ALTER TABLE players ADD COLUMN gems INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN mining_level INTEGER NOT NULL DEFAULT 1;
ALTER TABLE players ADD COLUMN mining_xp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN referred_by TEXT;
ALTER TABLE players ADD COLUMN referral_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN referral_earnings INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN claimed_referral_milestones TEXT NOT NULL DEFAULT '[]';
ALTER TABLE players ADD COLUMN referred_users TEXT NOT NULL DEFAULT '[]';
ALTER TABLE players ADD COLUMN gem_exchange_log TEXT NOT NULL DEFAULT '[]';
